### PR TITLE
Fix GPU issue

### PR DESCRIPTION
**Pull request by ZebinYang**

### CODE REVIEW

**Comment by JDE65** [comment]
I have an issue: "No module named 'piml' appears during the fitting phase.
It is impossible to install PiML with a pip install : no matching distribution found for piml...

**Comment by ZebinYang** [comment]
@JDE65 I just submitted a fix. Can you try again?

**Comment by JDE65** [comment]
You mean retry to install GAMINet and run it?

**Comment by ZebinYang** [comment]
> You mean retry to install GAMINet and run it?

Yes.

**Comment by JDE65** [comment]
It works fine but I still face an issue: When the warm_start=False, if I try to run GAMINetClassifier a second time (for example a model1 and a model2 trained on different train-sets), I get an error "element 0 of tensors does not require grad and does not have a grad_fn".
Do you know how to correct this?

**Comment by ZebinYang** [comment]
Can you put the codes here so that I can investigate?

**Comment by JDE65** [comment]
I'll do (I am currently not at office)
I don't do anything special. It is just that I cannot run twice the GAMINetClassifier within the same console.
Thanks


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
